spring.application.name=accommodation-rental

spring.datasource.url=jdbc:postgresql://localhost:5433/accommodation_rental
spring.datasource.username=emt
spring.datasource.password=emt

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
app.materialized-view-refresh-rate-ms=60000

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration


app.jwt.secret=VGhpcy1pcy1hLXNlY3JldC1qd3Qta2V5LWZvci1FTVQtTGFicy0yMDI2LXdpdGgtMzItYnl0ZXM=
app.jwt.expiration-ms=86400000

server.port=8080